--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t dvohra/node-server ."
      - "docker tag dvohra/node-server dvohra/node-server:latest"
      - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
  post_build: 
    commands: 
      - "echo Build completed on `date`"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"doanminhtien\" --password=\"mt1910941995\""
  artifacts:
    files: imagedefinitions.json
version: 0.1
