--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t dvohra/node-server ."
      - "docker tag dvohra/node-server dvohra/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"doanminhtien\" --password=\"mt1910941995\""
artifacts:
  files: imagedefinitions.json
version: 0.1
